// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLQ_kILyk_db62WJVdDVwwWSrdFlexiQ',
    appId: '1:568909881048:web:e85d7c931af986c942c1ad',
    messagingSenderId: '568909881048',
    projectId: 'idxtestflutter',
    authDomain: 'idxtestflutter.firebaseapp.com',
    storageBucket: 'idxtestflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGcCsRA0IWRDgi0vXfCDYvtXdbK69P7Gc',
    appId: '1:568909881048:android:f350b6e79f86056e42c1ad',
    messagingSenderId: '568909881048',
    projectId: 'idxtestflutter',
    storageBucket: 'idxtestflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZUOmkKk6bgfjkSnZeF3aqaKvcSYJtMlw',
    appId: '1:568909881048:ios:63f62de15bdeb14e42c1ad',
    messagingSenderId: '568909881048',
    projectId: 'idxtestflutter',
    storageBucket: 'idxtestflutter.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
